CREATE TABLE IF NOT EXISTS up_tasks_task
(
	ID           INT AUTO_INCREMENT,
	TITLE        VARCHAR(512) NOT NULL,
	COMPLETED    BOOLEAN      NOT NULL DEFAULT FALSE,
	CREATED_AT   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT   DATETIME     NULL     DEFAULT NULL,
	COMPLETED_AT DATETIME     NULL     DEFAULT NULL,
	PRIMARY KEY (ID)
);